<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
        <label class="group-name" for="api_token">API Token</label>
        <div class="group-controls">
		    <input type="password" name="api_token" value="<?php echo $this->getApiToken() ?>" />
        </div>
    </div>

    <div class="form-group">
        <label class="group-name" for="s">Space ID</label>
        <div class="group-controls">
		    <input type="input" name="space_id" value="<?php echo $this->getSpaceId() ?>" />
        </div>
    </div>

    <div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
		</div>
	</div>
</form>